language: php
php:
  - '5.6'
branches:
  except:
    - master
    - /^feature\//
env:
  global:
    # GH_TOKEN
    - secure: "G6Jel7GNvcX2Wbx2O0m24Owi4g+MB3dN/vVsKigUk0OaYdKj5HAIIA+FQtsjnZe5w8SsmKEeQULnLOK/5usqvKW1h/3xh8FFHXzFXjYETFA56M6USRXm03QmYF3ZmdLm1IATz8l/PLbsKYJHprAJ/A+UXKew+EQkLuxfuPnZ0cYBWNlQwI0ySYbzSWgYtr0PPEgG6ikqLT1G6WLCArSebtfMHqn5Vf65WmNBrnMdmLqT3YnKiBev4FoZNf+SJ2R0ro3lM/246HKsVUyQcKfs2WoREry5FS5RIOZxLM6B1mwOX8DLIq2Wu+IFxxTDKTUyJuCtz/eoH9zOZDYZQ5DrBlV47DzqSbPkwe/AGUyv9KgeUm95MwPsmAT7cegdDq3T2RI+jvdsHOILwUUa91rgj6Qg5xxv65ZJZqe18yjc5CCpLGJMc945BdkNXTCkQ6RBI4wx3qHIoxf+cT5GmCJFMdfhKVPRJzOVEmANiUyPrBENhFxAIZm2om5YLjnldFtRQCK7CfVi5rNgl/EKXeC5fS1Kypp3h2WJ5cigC9SMmVhyskGwE4EYBuxmTpsty1ubo/LMntdMDdZ752KXo8N04ccLwLISJ9UVGrXx48+v7U6unxGqYn75Mv43W21isjFt1hKGyKMMhE9qE2N76MKb9VgG8duRFd6SKeZCzY+oI88="
before_install:
  - composer self-update
  - if [ ! -z "$TRAVIS_TAG" ]; then
      gem install sass;
      npm install -g gulp &>/dev/null;
    fi
install:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      npm install &>/dev/null;
      cd $TRAVIS_BUILD_DIR/platforms/common && npm install &>/dev/null;
      cd $TRAVIS_BUILD_DIR/assets/common && npm install &>/dev/null;
      cd $TRAVIS_BUILD_DIR/engines/common/nucleus && npm install &>/dev/null;
    fi
  - cd $TRAVIS_BUILD_DIR/src && composer install --no-dev;
  - cd $TRAVIS_BUILD_DIR/bin/build && composer install --no-dev
script:
  - export SHORT_COMMIT=$(echo $TRAVIS_COMMIT | cut -c1-9)
  - echo "Branch ($TRAVIS_BRANCH)"
  - cd $TRAVIS_BUILD_DIR/bin/build
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      cd $TRAVIS_BUILD_DIR/platforms/joomla;
      sed -i -e "s/<version>.*<\/version>/<version>dev-$SHORT_COMMIT<\/version>/g" pkg_gantry5.xml;
      cd $TRAVIS_BUILD_DIR/bin/build;
      php build.php dev -propertyfile release.ini -Dpackage_dir=$TRAVIS_BUILD_DIR/repo_pkgs -Dstr.fileversion=_develop;
    elif [ ! -z "$TRAVIS_TAG" ]; then
      php build.php prod -propertyfile release.ini -Dpackage_dir=$TRAVIS_BUILD_DIR/repo_pkgs -Dxml.version=$TRAVIS_TAG;
    else
      echo "($TRAVIS_BRANCH) is not a supported branch for builds";
    fi
before_deploy:
  - export PROJ_PKGS_PATH=$TRAVIS_BUILD_DIR/repo_pkgs
  - export PROJ_PKGS=$HOME/build/$TRAVIS_REPO_SLUG/repo_pkgs/*.zip
deploy:
  - provider: releases
    api_key:
      secure: "WnqXVzEa9Ol5B1X9404E7DrWKsB40C3zgsj9I0yoR7t8UDw6BHOhxWb0Mhapxa08yXcdky/nQv7rDytJiOVJxxOCLA0QajSEBoLFb9etyyYt0UA+LHuYQWjNbwNpCvKYuAnd8bsMrSpM8Qj403OkvaoQ2hLjONumAHzVpcNnMETiWH/j1ZZXevSGH5sS0kaL9GcHHj3615PrfejgQpoXPjD+w/uxOwsr3+9R4PfxVq9Fx6nJnAZmWfRc9Der4rumMOtgvs+/OZksFYk/My74j2YJm8VlA9DbYo9SW8QtdNGzIPdxgkkMZ4uuq5OBh/rYIvWsv/eZAC3hAaqjRfx2V+I45WMc9KHeRMHxQdfWF3BNPVv8d7jELxKT33wNW4jNiRnjtjV1MpJuHfC4dklQAD60taVPlZrfrl5oKjLmFjfSaoRkzx3vaXiO/MiF8j1B8DFsmfikR079Ct3cA7vSLhdg5Goe8hwgnBFkEzg2CGPx53L50t2xWJ5d2Gux5H9JaF98i3Yeobd01hY9jWR8ewKQUibgTId4BaZ9jlNY2sE86ZqUyXdmdOx3hJsa12EqgKwGh1nrtStcHX9/a0BcFRd8dGkZ5vSS+VJ3kKc4Txum8mmGnJkoKfaviktUrh8Pq41RKmpdT6ibtPFP+UMtgBDdK3Eg34TJByNt5iHkFMY="
    skip_cleanup: true
    file_glob: true
    file: "${PROJ_PKGS}"
    on:
      repo: gantry/gantry5
      tags: true
  - provider: s3
    access_key_id: AKIAIGEIWVFNBMVSH2UA
    secret_access_key:
      secure: GdgT5VmhK5JBC966psroCH3s8mQStdrQhhcSsnM1sVtT2xI0YgTDQvLJQMOLlas+fgN/3uvfaW4pPQYF+HpZ1arP8ByCprziTqY+F/zRSx9V45VMz96pZhHIcSOqibeqVKYV027Vfg3My4w/uY9zpR7eT7onyHp0CAouOfy3uBfoW1qAb4/V5kUXbxZx53hYj6bjAV8gbTy34Ood+H7zLtSv+jXmoQWzPUfsuAAXtB5NaUYg0uPXNbTCU2hsvA6Cb/v6twVGTCBToYpJgDm/I0aqvPUqxkO+fvjLgI/aWL8Dzqf9Y2tacW22mgTJO2fmaLJdhZmf5NZWQgqWWbjuC92GNouyCYctC6iqyc/WLB6GEqe+pUb2Vlrs3lLkUrLnn2ey2vcfK8P7Uj12ZU0Fri/X2X8kh1kN4pK8kGReMMxCMvz93tiNRRROz/rsy4SsLrAcohPHoO2lHmeMsgauUZxFPtu98UfDzG/AFld3uagCcadHe+7z0nVguLNqZh79XEIV4zUsWIvNk6Kw/dJZ34IZN8gU0Zz/jM+XSLMH8eMCNwKPY0KuOoUPtlJicxOgYSKz/mAITO9mHqPMf2Bc739DKDACljLjQGEk5cg0jqAtA7IFdZvGL1tlf+COTUokZ+XAJFkaFGNTmyuDi22Er3nQdbqx5zborhUYf4ixiPs=
    bucket: gantry5
    local-dir: "$PROJ_PKGS_PATH"
    upload-dir: nightly
    skip_cleanup: true
    acl: public_read
    on:
      branch: develop
after_deploy:
  - echo "Branch ($TRAVIS_BRANCH) - Tag ($TRAVIS_TAG)"
  - if [ ! -z "$TRAVIS_TAG" ]; then
      git config user.email "bot@travis-ci.org";
      git config user.name "Travis CI";
      rm -rf $PROJ_PKGS_PATH;
      git checkout -b master;
      git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*";
      git fetch --quiet;
      cd $TRAVIS_BUILD_DIR/bin/build;
      php build.php prod-versions -propertyfile release.ini -Dupdate_versions=true -Dxml.version=$TRAVIS_TAG;
      cd $TRAVIS_BUILD_DIR;
      git commit -am "Release [$TRAVIS_TAG] - Automatic Version Number Updates";
      git push --force --quiet --set-upstream https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master:master &>/dev/null;
    fi
